### Spring properties
#Serice registers
spring:
  application:
    name: accounts-microservice
 
 #Discovery
 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
server:
  port: 2222
  
 erro:
  whitelabel:
    enabled: false